spring.application.name=coreservices

#Server Port
server.port=8001

#PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d8ntqf28qa3s73fgk460-a.oregon-postgres.render.com:5432/project_gfu3

spring.datasource.username=postgres_user

spring.datasource.password=HPfQNQq2eQVbUSUip1vbvpNj5Vo3xIM9

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=productapplicationcatlog@gmail.com
spring.mail.password=dbms@project
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true